name       : libtraceevent
version    : 1.7.3
release    : 1
source     :
    - https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/snapshot/libtraceevent-1.7.3.tar.gz : 097b72e0d907f3107825fb2edf0188324bf70dc9da360f6efa68dc484ffde541
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : libtraceevent is a library to parse raw trace event formats.
description: |
    libtraceevent is a library to parse raw trace event formats.
builddeps  :
    - asciidoc
    - xmlto
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    find $installdir -type f -name '*.a' -delete
